version: '2'
services:
  https:
    working_dir: /usr/app/
    image: node:latest
    command: npm run start
    volumes:
      - .:/usr/app/
    tty: true
  nginx:
    depends_on:
      - https
    tty: true
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80